[feature/#56] 로그인 서버 기능 구현
woowa-techcamp-2021/baemin-17 pull request #65
Opened 2021-07-08 17:37 UTC by TsooranKim

- 로그인 페이지와 서버 로그인 기능 구현
- 메인페이지에 로그인 사용자 정보 렌더
- 로그아웃 기능 구현

2021-07-08 18:38 UTC, KangyeolLee requested changes

2021-07-08 18:38 UTC, KangyeolLee commented on public/stylesheets/index.css
> +.main-page .user a, .main-page .user .logged-in {
로그아웃 상태에서는 `.main-page .user a` 요소가 하나 존재합니다.

그러나 로그인 상태에서는

- `.main-page .user .logged-in` 요소 안에
-  `.main-page .user a` (로그아웃 문구) 가 들어있어

`padding: 15px`이 중복 적용 됩니다.

때문에 로그인 된 상태에서 로그아웃 버튼을 누를 때
서로 다른 `padding` 값으로 인해 UI가 조금씩 뒤틀리는 현상이 발생합니다.

이는 UX에 안 좋은 영향을 미칠 수 있기 때문에
관련해서 동일한 레이아웃을 지정하는 것이 좋다고 생각합니다.

아래와 같이 별도로 해당 태그에 스타일링을 지정하면 좋을 거 같습니다.


```css
.main-page .user a.logout {
  padding: 0;
}
```

2021-07-08 18:38 UTC, KangyeolLee commented on public/stylesheets/login.css
> +  color: #ca3c3c;
```suggestion
  color: 'red'
```

모든 에러메시지들은 빨간색(`red`)을 사용하고 있는데

통일성을 위해 동일한 색상을 사용하는 것이 어떨까요?

2021-07-08 18:38 UTC, KangyeolLee commented on views/login.pug
> +          p.login-error-message 로그인 오류: #{error}
로그인 오류 메시지는 로그인에 실패했을 때 출력됩니다.

로그인이 실패하면 기존 인풋 값이 지워지고

로그인 버튼 상단에 에러메시지가 출력되고 있습니다.

이때 기존 인풋의 경우에는 아무런 값을 입력하지 않았을 때 역시

경고 메시지를 출력하게 되어있는데

이때의 경고메시지와 로그인 에러 메시지가 서로 겹치는 현상이 발생합니다.

만약 비어있는 값 입력으로 인해 경고 메시지가 뜨게 되는 경우

서버에서 전송된 로그인 에러 메시지는 숨김처리 되어야 할 것 같습니다.

`login.js` 파일에 다음과 같은 메서드를 구현하여 해당 작업을 처리할 수 있을 거 같습니다.

```js
  this.hideLoginErrorMessage = function () {
    const $serverErrorMessage = $login.querySelector(".login-error-message");

    if ($serverErrorMessage) {
      $serverErrorMessage.style.display = "none";
    }
  };
```

그리고 위의 메서드를 빈 입력값 경고 메시지 토글 함수에 추가합니다.

```js
  this.toggleEmailWarningMessage = function (userEmail) {
    if (!userEmail) {
      this.$emailWarningMsg.style.display = "block";
      this.$emailInput.style.borderBottomColor = "red";
      this.hideLoginErrorMessage();  // 이 부분만 추가
      return false;
    }

    this.$emailWarningMsg.style.display = "none";
    this.$emailInput.style.borderBottomColor = "#d7d7d7";
    return true;
  };

  this.togglePasswordWarningMessage = function (userPassword) {
    if (!userPassword) {
      this.$passwordWarningMsg.style.display = "block";
      this.$passwordInput.style.borderBottomColor = "red";
      this.hideLoginErrorMessage();  // 이 부분만 추가
      return false;
    }

    this.$passwordWarningMsg.style.display = "none";
    this.$passwordInput.style.borderBottomColor = "#d7d7d7";
    return true;
  };
```

2021-07-08 18:44 UTC, KangyeolLee requested changes

2021-07-08 18:44 UTC, KangyeolLee commented on routes/index.js
> +    res.render('login', { error: '존재하지 않는 유저정보입니다.' });
`res.render` 를 통해 템플릿을 넣어주는 방식은 대부분의 상황에서 문제 없이 동작하나 다음과 같은 치명적인 단점이 있습니다.

로그인 에러 메시지가 발생하는 경우, 해당 요청은 `POST` 메서드에서 발생하고,

`POST` 메서드에서 렌더링 되었기 때문에 이후 새로고침을 하더라도 `GET`이 아닌 `POST` 요청으로 계속 `login` 문서를 서버에 요청하게 됩니다.

이 경우 로그인 에러메시지가 새로고침을 하더라도 사라지지 않는 치명적인 문제가 발생합니다.

이는 회원가입 기능을 구현할 때도 동일하게 발생했던 문제인데 세션이나 쿼리스트링을 이용해서 `res.redirect`를 해야할 것 같습니다. 만약 세션을 이용한다면 다음과 같이 수정할 수 있을 것 같습니다.

먼저 `router.post('/login, ...)` 라우터 내부를 아래와 같이 수정합니다.

```suggestion
    req.session.loginError = "존재하지 않는 유저정보입니다.";
    res.redirect("/login");
```
<br/>

그리고 `router.get('/login', ...`) 라우터로 이동하여 다음과 같이 수정합니다.

```js
router.get("/login", function (req, res, next) {
  const loginError = req.session?.loginError;

  if (loginError) {
    delete req.session.loginError;
    res.render("login", { error: loginError });
    return;
  }

  res.render("login");
});
```

2021-07-09 01:23 UTC, KangyeolLee commented on routes/index.js
> +router.post("/login", async function (req, res) {
오류 없는걸 다시 확인했습니다.
죄송합니다.

2021-07-09 01:25 UTC, KangyeolLee commented on routes/index.js
> +router.get('/logout', function (req, res) {
오류 없는걸 다시 확인했습니다.
죄송합니다.

2021-07-09 01:36 UTC, TsooranKim commented on public/stylesheets/index.css
> +.main-page .user a, .main-page .user .logged-in {
오오 예리하십니다. 수정하도록 하겠습니다.

2021-07-09 01:37 UTC, TsooranKim commented on routes/index.js
> +    res.render('login', { error: '존재하지 않는 유저정보입니다.' });
session으로 옮겨서 작업하도록 하겠습니다~

2021-07-09 01:39 UTC, TsooranKim commented on views/login.pug
> +          p.login-error-message 로그인 오류: #{error}
으흠~ 수정하도록 하겠습니다.

2021-07-09 01:56 UTC, KangyeolLee approved these changes
수고하셨습니다 짝짝짝

2021-07-09 01:56 UTC, merged